/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as AuthenticatedSocialRouteImport } from './routes/_authenticated/social'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedServersRouteImport } from './routes/_authenticated/servers'
import { Route as AuthenticatedScriptforgeRouteImport } from './routes/_authenticated/scriptforge'
import { Route as AuthenticatedRobloxRouteImport } from './routes/_authenticated/roblox'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated/premium'
import { Route as AuthenticatedPhase7RouteImport } from './routes/_authenticated/phase7'
import { Route as AuthenticatedPhase6RouteImport } from './routes/_authenticated/phase6'
import { Route as AuthenticatedPhase5RouteImport } from './routes/_authenticated/phase5'
import { Route as AuthenticatedPhase4RouteImport } from './routes/_authenticated/phase4'
import { Route as AuthenticatedPhase3RouteImport } from './routes/_authenticated/phase3'
import { Route as AuthenticatedPhase2RouteImport } from './routes/_authenticated/phase2'
import { Route as AuthenticatedPhase1RouteImport } from './routes/_authenticated/phase1'
import { Route as AuthenticatedOwnerRouteImport } from './routes/_authenticated/owner'
import { Route as AuthenticatedNexusRouteImport } from './routes/_authenticated/nexus'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedImagesRouteImport } from './routes/_authenticated/images'
import { Route as AuthenticatedHubRouteImport } from './routes/_authenticated/hub'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedExportRouteImport } from './routes/_authenticated/export'
import { Route as AuthenticatedDiscordRouteImport } from './routes/_authenticated/discord'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as ApiPublicLurisRouteImport } from './routes/api/public/luris'
import { Route as ApiPublicDiscordInteractionsRouteImport } from './routes/api/public/discord/interactions'
import { Route as ApiPublicLurisV1ModelsRouteImport } from './routes/api/public/luris/v1/models'
import { Route as ApiPublicLurisV1ChatCompletionsRouteImport } from './routes/api/public/luris/v1/chat/completions'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSocialRoute = AuthenticatedSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServersRoute = AuthenticatedServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScriptforgeRoute =
  AuthenticatedScriptforgeRouteImport.update({
    id: '/scriptforge',
    path: '/scriptforge',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRobloxRoute = AuthenticatedRobloxRouteImport.update({
  id: '/roblox',
  path: '/roblox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPhase7Route = AuthenticatedPhase7RouteImport.update({
  id: '/phase7',
  path: '/phase7',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPhase6Route = AuthenticatedPhase6RouteImport.update({
  id: '/phase6',
  path: '/phase6',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPhase5Route = AuthenticatedPhase5RouteImport.update({
  id: '/phase5',
  path: '/phase5',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPhase4Route = AuthenticatedPhase4RouteImport.update({
  id: '/phase4',
  path: '/phase4',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPhase3Route = AuthenticatedPhase3RouteImport.update({
  id: '/phase3',
  path: '/phase3',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPhase2Route = AuthenticatedPhase2RouteImport.update({
  id: '/phase2',
  path: '/phase2',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPhase1Route = AuthenticatedPhase1RouteImport.update({
  id: '/phase1',
  path: '/phase1',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOwnerRoute = AuthenticatedOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNexusRoute = AuthenticatedNexusRouteImport.update({
  id: '/nexus',
  path: '/nexus',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImagesRoute = AuthenticatedImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHubRoute = AuthenticatedHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExportRoute = AuthenticatedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiscordRoute = AuthenticatedDiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicLurisRoute = ApiPublicLurisRouteImport.update({
  id: '/api/public/luris',
  path: '/api/public/luris',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscordInteractionsRoute =
  ApiPublicDiscordInteractionsRouteImport.update({
    id: '/api/public/discord/interactions',
    path: '/api/public/discord/interactions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLurisV1ModelsRoute = ApiPublicLurisV1ModelsRouteImport.update({
  id: '/v1/models',
  path: '/v1/models',
  getParentRoute: () => ApiPublicLurisRoute,
} as any)
const ApiPublicLurisV1ChatCompletionsRoute =
  ApiPublicLurisV1ChatCompletionsRouteImport.update({
    id: '/v1/chat/completions',
    path: '/v1/chat/completions',
    getParentRoute: () => ApiPublicLurisRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discord': typeof AuthenticatedDiscordRoute
  '/export': typeof AuthenticatedExportRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/hub': typeof AuthenticatedHubRoute
  '/images': typeof AuthenticatedImagesRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/nexus': typeof AuthenticatedNexusRoute
  '/owner': typeof AuthenticatedOwnerRoute
  '/phase1': typeof AuthenticatedPhase1Route
  '/phase2': typeof AuthenticatedPhase2Route
  '/phase3': typeof AuthenticatedPhase3Route
  '/phase4': typeof AuthenticatedPhase4Route
  '/phase5': typeof AuthenticatedPhase5Route
  '/phase6': typeof AuthenticatedPhase6Route
  '/phase7': typeof AuthenticatedPhase7Route
  '/premium': typeof AuthenticatedPremiumRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/roblox': typeof AuthenticatedRobloxRoute
  '/scriptforge': typeof AuthenticatedScriptforgeRoute
  '/servers': typeof AuthenticatedServersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/social': typeof AuthenticatedSocialRoute
  '/s/$slug': typeof SSlugRoute
  '/api/public/luris': typeof ApiPublicLurisRouteWithChildren
  '/api/public/discord/interactions': typeof ApiPublicDiscordInteractionsRoute
  '/api/public/luris/v1/models': typeof ApiPublicLurisV1ModelsRoute
  '/api/public/luris/v1/chat/completions': typeof ApiPublicLurisV1ChatCompletionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discord': typeof AuthenticatedDiscordRoute
  '/export': typeof AuthenticatedExportRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/hub': typeof AuthenticatedHubRoute
  '/images': typeof AuthenticatedImagesRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/nexus': typeof AuthenticatedNexusRoute
  '/owner': typeof AuthenticatedOwnerRoute
  '/phase1': typeof AuthenticatedPhase1Route
  '/phase2': typeof AuthenticatedPhase2Route
  '/phase3': typeof AuthenticatedPhase3Route
  '/phase4': typeof AuthenticatedPhase4Route
  '/phase5': typeof AuthenticatedPhase5Route
  '/phase6': typeof AuthenticatedPhase6Route
  '/phase7': typeof AuthenticatedPhase7Route
  '/premium': typeof AuthenticatedPremiumRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/roblox': typeof AuthenticatedRobloxRoute
  '/scriptforge': typeof AuthenticatedScriptforgeRoute
  '/servers': typeof AuthenticatedServersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/social': typeof AuthenticatedSocialRoute
  '/s/$slug': typeof SSlugRoute
  '/api/public/luris': typeof ApiPublicLurisRouteWithChildren
  '/api/public/discord/interactions': typeof ApiPublicDiscordInteractionsRoute
  '/api/public/luris/v1/models': typeof ApiPublicLurisV1ModelsRoute
  '/api/public/luris/v1/chat/completions': typeof ApiPublicLurisV1ChatCompletionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/discord': typeof AuthenticatedDiscordRoute
  '/_authenticated/export': typeof AuthenticatedExportRoute
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/hub': typeof AuthenticatedHubRoute
  '/_authenticated/images': typeof AuthenticatedImagesRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/nexus': typeof AuthenticatedNexusRoute
  '/_authenticated/owner': typeof AuthenticatedOwnerRoute
  '/_authenticated/phase1': typeof AuthenticatedPhase1Route
  '/_authenticated/phase2': typeof AuthenticatedPhase2Route
  '/_authenticated/phase3': typeof AuthenticatedPhase3Route
  '/_authenticated/phase4': typeof AuthenticatedPhase4Route
  '/_authenticated/phase5': typeof AuthenticatedPhase5Route
  '/_authenticated/phase6': typeof AuthenticatedPhase6Route
  '/_authenticated/phase7': typeof AuthenticatedPhase7Route
  '/_authenticated/premium': typeof AuthenticatedPremiumRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/roblox': typeof AuthenticatedRobloxRoute
  '/_authenticated/scriptforge': typeof AuthenticatedScriptforgeRoute
  '/_authenticated/servers': typeof AuthenticatedServersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/social': typeof AuthenticatedSocialRoute
  '/s/$slug': typeof SSlugRoute
  '/api/public/luris': typeof ApiPublicLurisRouteWithChildren
  '/api/public/discord/interactions': typeof ApiPublicDiscordInteractionsRoute
  '/api/public/luris/v1/models': typeof ApiPublicLurisV1ModelsRoute
  '/api/public/luris/v1/chat/completions': typeof ApiPublicLurisV1ChatCompletionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/chat'
    | '/dashboard'
    | '/discord'
    | '/export'
    | '/friends'
    | '/hub'
    | '/images'
    | '/marketplace'
    | '/nexus'
    | '/owner'
    | '/phase1'
    | '/phase2'
    | '/phase3'
    | '/phase4'
    | '/phase5'
    | '/phase6'
    | '/phase7'
    | '/premium'
    | '/profile'
    | '/roblox'
    | '/scriptforge'
    | '/servers'
    | '/settings'
    | '/social'
    | '/s/$slug'
    | '/api/public/luris'
    | '/api/public/discord/interactions'
    | '/api/public/luris/v1/models'
    | '/api/public/luris/v1/chat/completions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/chat'
    | '/dashboard'
    | '/discord'
    | '/export'
    | '/friends'
    | '/hub'
    | '/images'
    | '/marketplace'
    | '/nexus'
    | '/owner'
    | '/phase1'
    | '/phase2'
    | '/phase3'
    | '/phase4'
    | '/phase5'
    | '/phase6'
    | '/phase7'
    | '/premium'
    | '/profile'
    | '/roblox'
    | '/scriptforge'
    | '/servers'
    | '/settings'
    | '/social'
    | '/s/$slug'
    | '/api/public/luris'
    | '/api/public/discord/interactions'
    | '/api/public/luris/v1/models'
    | '/api/public/luris/v1/chat/completions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/sitemap.xml'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/discord'
    | '/_authenticated/export'
    | '/_authenticated/friends'
    | '/_authenticated/hub'
    | '/_authenticated/images'
    | '/_authenticated/marketplace'
    | '/_authenticated/nexus'
    | '/_authenticated/owner'
    | '/_authenticated/phase1'
    | '/_authenticated/phase2'
    | '/_authenticated/phase3'
    | '/_authenticated/phase4'
    | '/_authenticated/phase5'
    | '/_authenticated/phase6'
    | '/_authenticated/phase7'
    | '/_authenticated/premium'
    | '/_authenticated/profile'
    | '/_authenticated/roblox'
    | '/_authenticated/scriptforge'
    | '/_authenticated/servers'
    | '/_authenticated/settings'
    | '/_authenticated/social'
    | '/s/$slug'
    | '/api/public/luris'
    | '/api/public/discord/interactions'
    | '/api/public/luris/v1/models'
    | '/api/public/luris/v1/chat/completions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SSlugRoute: typeof SSlugRoute
  ApiPublicLurisRoute: typeof ApiPublicLurisRouteWithChildren
  ApiPublicDiscordInteractionsRoute: typeof ApiPublicDiscordInteractionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/social': {
      id: '/_authenticated/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AuthenticatedSocialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servers': {
      id: '/_authenticated/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof AuthenticatedServersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scriptforge': {
      id: '/_authenticated/scriptforge'
      path: '/scriptforge'
      fullPath: '/scriptforge'
      preLoaderRoute: typeof AuthenticatedScriptforgeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roblox': {
      id: '/_authenticated/roblox'
      path: '/roblox'
      fullPath: '/roblox'
      preLoaderRoute: typeof AuthenticatedRobloxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/phase7': {
      id: '/_authenticated/phase7'
      path: '/phase7'
      fullPath: '/phase7'
      preLoaderRoute: typeof AuthenticatedPhase7RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/phase6': {
      id: '/_authenticated/phase6'
      path: '/phase6'
      fullPath: '/phase6'
      preLoaderRoute: typeof AuthenticatedPhase6RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/phase5': {
      id: '/_authenticated/phase5'
      path: '/phase5'
      fullPath: '/phase5'
      preLoaderRoute: typeof AuthenticatedPhase5RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/phase4': {
      id: '/_authenticated/phase4'
      path: '/phase4'
      fullPath: '/phase4'
      preLoaderRoute: typeof AuthenticatedPhase4RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/phase3': {
      id: '/_authenticated/phase3'
      path: '/phase3'
      fullPath: '/phase3'
      preLoaderRoute: typeof AuthenticatedPhase3RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/phase2': {
      id: '/_authenticated/phase2'
      path: '/phase2'
      fullPath: '/phase2'
      preLoaderRoute: typeof AuthenticatedPhase2RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/phase1': {
      id: '/_authenticated/phase1'
      path: '/phase1'
      fullPath: '/phase1'
      preLoaderRoute: typeof AuthenticatedPhase1RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nexus': {
      id: '/_authenticated/nexus'
      path: '/nexus'
      fullPath: '/nexus'
      preLoaderRoute: typeof AuthenticatedNexusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/images': {
      id: '/_authenticated/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof AuthenticatedImagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hub': {
      id: '/_authenticated/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof AuthenticatedHubRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/export': {
      id: '/_authenticated/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthenticatedExportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/discord': {
      id: '/_authenticated/discord'
      path: '/discord'
      fullPath: '/discord'
      preLoaderRoute: typeof AuthenticatedDiscordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/luris': {
      id: '/api/public/luris'
      path: '/api/public/luris'
      fullPath: '/api/public/luris'
      preLoaderRoute: typeof ApiPublicLurisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/interactions': {
      id: '/api/public/discord/interactions'
      path: '/api/public/discord/interactions'
      fullPath: '/api/public/discord/interactions'
      preLoaderRoute: typeof ApiPublicDiscordInteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/luris/v1/models': {
      id: '/api/public/luris/v1/models'
      path: '/v1/models'
      fullPath: '/api/public/luris/v1/models'
      preLoaderRoute: typeof ApiPublicLurisV1ModelsRouteImport
      parentRoute: typeof ApiPublicLurisRoute
    }
    '/api/public/luris/v1/chat/completions': {
      id: '/api/public/luris/v1/chat/completions'
      path: '/v1/chat/completions'
      fullPath: '/api/public/luris/v1/chat/completions'
      preLoaderRoute: typeof ApiPublicLurisV1ChatCompletionsRouteImport
      parentRoute: typeof ApiPublicLurisRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiscordRoute: typeof AuthenticatedDiscordRoute
  AuthenticatedExportRoute: typeof AuthenticatedExportRoute
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
  AuthenticatedHubRoute: typeof AuthenticatedHubRoute
  AuthenticatedImagesRoute: typeof AuthenticatedImagesRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedNexusRoute: typeof AuthenticatedNexusRoute
  AuthenticatedOwnerRoute: typeof AuthenticatedOwnerRoute
  AuthenticatedPhase1Route: typeof AuthenticatedPhase1Route
  AuthenticatedPhase2Route: typeof AuthenticatedPhase2Route
  AuthenticatedPhase3Route: typeof AuthenticatedPhase3Route
  AuthenticatedPhase4Route: typeof AuthenticatedPhase4Route
  AuthenticatedPhase5Route: typeof AuthenticatedPhase5Route
  AuthenticatedPhase6Route: typeof AuthenticatedPhase6Route
  AuthenticatedPhase7Route: typeof AuthenticatedPhase7Route
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRobloxRoute: typeof AuthenticatedRobloxRoute
  AuthenticatedScriptforgeRoute: typeof AuthenticatedScriptforgeRoute
  AuthenticatedServersRoute: typeof AuthenticatedServersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSocialRoute: typeof AuthenticatedSocialRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiscordRoute: AuthenticatedDiscordRoute,
  AuthenticatedExportRoute: AuthenticatedExportRoute,
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
  AuthenticatedHubRoute: AuthenticatedHubRoute,
  AuthenticatedImagesRoute: AuthenticatedImagesRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedNexusRoute: AuthenticatedNexusRoute,
  AuthenticatedOwnerRoute: AuthenticatedOwnerRoute,
  AuthenticatedPhase1Route: AuthenticatedPhase1Route,
  AuthenticatedPhase2Route: AuthenticatedPhase2Route,
  AuthenticatedPhase3Route: AuthenticatedPhase3Route,
  AuthenticatedPhase4Route: AuthenticatedPhase4Route,
  AuthenticatedPhase5Route: AuthenticatedPhase5Route,
  AuthenticatedPhase6Route: AuthenticatedPhase6Route,
  AuthenticatedPhase7Route: AuthenticatedPhase7Route,
  AuthenticatedPremiumRoute: AuthenticatedPremiumRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRobloxRoute: AuthenticatedRobloxRoute,
  AuthenticatedScriptforgeRoute: AuthenticatedScriptforgeRoute,
  AuthenticatedServersRoute: AuthenticatedServersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSocialRoute: AuthenticatedSocialRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiPublicLurisRouteChildren {
  ApiPublicLurisV1ModelsRoute: typeof ApiPublicLurisV1ModelsRoute
  ApiPublicLurisV1ChatCompletionsRoute: typeof ApiPublicLurisV1ChatCompletionsRoute
}

const ApiPublicLurisRouteChildren: ApiPublicLurisRouteChildren = {
  ApiPublicLurisV1ModelsRoute: ApiPublicLurisV1ModelsRoute,
  ApiPublicLurisV1ChatCompletionsRoute: ApiPublicLurisV1ChatCompletionsRoute,
}

const ApiPublicLurisRouteWithChildren = ApiPublicLurisRoute._addFileChildren(
  ApiPublicLurisRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SSlugRoute: SSlugRoute,
  ApiPublicLurisRoute: ApiPublicLurisRouteWithChildren,
  ApiPublicDiscordInteractionsRoute: ApiPublicDiscordInteractionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
