INSERT INTO public.marketplace_items (title, description, category, item_type, price_coins, tags, content, approved, is_featured)
VALUES
('Aura Dragão','Fogo de dragão girando ao redor da sua foto.','Avatar Effects','avatar_effect',420,ARRAY['fx-dragon','animated'],NULL,true,true),
('Aura Anjo','Halo suave e dourado, puro e brilhante.','Avatar Effects','avatar_effect',380,ARRAY['fx-angel','animated'],NULL,true,false),
('Aura Demônio','Espinhos vermelhos girando em sentido invertido.','Avatar Effects','avatar_effect',420,ARRAY['fx-demon','animated'],NULL,true,false),
('Aura Oceano','Ondas azuis pulsando devagar.','Avatar Effects','avatar_effect',260,ARRAY['fx-ocean','animated'],NULL,true,false),
('Aura Lavanda','Roxo pastel calminho.','Avatar Effects','avatar_effect',200,ARRAY['fx-lavender','animated'],NULL,true,false),
('Aura Chiclete','Rosa fofo com batida de coração.','Avatar Effects','avatar_effect',300,ARRAY['fx-bubblegum','animated'],NULL,true,true),
('Aura Trovão','Faíscas elétricas em stop-motion.','Avatar Effects','avatar_effect',340,ARRAY['fx-thunder','animated'],NULL,true,false),
('Aura Plasma','Plasma neon girando rapidinho.','Avatar Effects','avatar_effect',460,ARRAY['fx-plasma','animated'],NULL,true,true),
('Aura Cosmos','Estrelas e nebulosa girando devagar.','Avatar Effects','avatar_effect',500,ARRAY['fx-cosmos','animated'],NULL,true,true),
('Aura Esmeralda Fluida','Verde esmeralda líquido.','Avatar Effects','avatar_effect',280,ARRAY['fx-emerald-flow','animated'],NULL,true,false),
('Aura Sunset','Laranja e rosa de fim de tarde.','Avatar Effects','avatar_effect',240,ARRAY['fx-sunset','animated'],NULL,true,false),
('Aura Cromada','Metal polido girando.','Avatar Effects','avatar_effect',320,ARRAY['fx-chrome','animated'],NULL,true,false),
('Aura Coração da Luris','Feita pela Luris. Rosa e roxo pulsando no ritmo do coração.','Avatar Effects','avatar_effect',666,ARRAY['fx-luris-heart','animated','luris'],NULL,true,true),
('Nome Aurora','Gradiente animado azul/roxo/verde no seu nome.','Perfil','name_style',150,ARRAY['name-aurora'],'aurora',true,true),
('Nome Candy','Cores de doce se movendo.','Perfil','name_style',150,ARRAY['name-candy'],'candy',true,false),
('Nome Cromado','Metal escovado brilhante.','Perfil','name_style',120,ARRAY['name-chrome'],'chrome',true,false),
('Nome Matrix','Verde de terminal hacker.','Perfil','name_style',120,ARRAY['name-matrix'],'matrix',true,false),
('Nome Vazio','Cinza sombrio com brilho roxo.','Perfil','name_style',120,ARRAY['name-void'],'void',true,false),
('Nome Sunset','Degradê quente animado.','Perfil','name_style',140,ARRAY['name-sunset'],'sunset',true,false),
('Nome Holográfico','Ciano e magenta piscando.','Perfil','name_style',180,ARRAY['name-holo'],'holo',true,true),
('Nome Contorno Néon','Letras vazadas com contorno neon.','Perfil','name_style',160,ARRAY['name-outline'],'outline',true,false),
('Fonte Cyber Largo','Letras espaçadas em caixa alta.','Perfil','name_font',100,ARRAY['font-wide'],'wide',true,false),
('Fonte Small Caps','Serifada elegante em versaletes.','Perfil','name_font',100,ARRAY['font-tinycaps'],'tinycaps',true,false),
('Fundo Nightberry','Fundo escuro roxo/vinho para conversas.','Fundos de Chat','chat_background',90,ARRAY['bg-nightberry'],'linear-gradient(160deg, oklch(0.16 0.12 320), oklch(0.10 0.08 285))',true,false),
('Fundo Oceano Profundo','Azul profundo relaxante.','Fundos de Chat','chat_background',90,ARRAY['bg-ocean'],'linear-gradient(160deg, oklch(0.18 0.10 245), oklch(0.09 0.06 260))',true,false),
('Fundo Sakura','Rosa suave de primavera.','Fundos de Chat','chat_background',90,ARRAY['bg-sakura'],'linear-gradient(160deg, oklch(0.22 0.08 350), oklch(0.12 0.05 320))',true,true),
('Fundo Matrix','Verde terminal.','Fundos de Chat','chat_background',90,ARRAY['bg-matrix'],'linear-gradient(160deg, oklch(0.18 0.12 150), oklch(0.08 0.06 160))',true,false),
('Fundo Ouro Noturno','Preto com dourado.','Fundos de Chat','chat_background',110,ARRAY['bg-gold'],'linear-gradient(160deg, oklch(0.20 0.09 85), oklch(0.09 0.04 80))',true,false),
('Fundo Cosmos','Roxo espacial degradê.','Fundos de Chat','chat_background',110,ARRAY['bg-cosmos'],'radial-gradient(ellipse at top, oklch(0.24 0.16 295), oklch(0.07 0.04 285) 70%)',true,true);